from __future__ import annotations
from typing import TYPE_CHECKING, ClassVar

from rule_builder.rules import Has, HasAll, Rule

from .items import SplasherItem, SplasherPowerItem
from .locations import SplasherLocationOnEachLevel, SplasherPowerLocation, SplashersLocation
from .options import RandomizePowers
from .utils import SplasherUtils

if TYPE_CHECKING:
    from .world import SplasherWorld

class SplasherRules:
    @classmethod
    def set_rules(cls, world: SplasherWorld):
        cls.__add_splashers_rules(world)

        world.get_location(
            SplasherLocationOnEachLevel.CLEAR.fullname(21)
        ).place_locked_item(
            SplasherItem(SplasherItem.victory, world.player)
        )

        if world.options.randomize_powers == RandomizePowers.option_progressive:
            if world.options.progressive_water:
                cls.__add_progressive_power_rules_with_progressive_water()
            else:
                cls.__add_progressive_power_rules()
        else:
            cls.__add_power_rules()

            if (
                world.options.randomize_powers == RandomizePowers.option_off or
                world.options.randomize_powers == RandomizePowers.option_on_except_water
            ):
                world.get_location(
                    SplasherPowerLocation.WATER.fullname()
                ).place_locked_item(
                    SplasherItem(SplasherPowerItem.PROGRESSIVE_WATER if world.options.progressive_water else SplasherPowerItem.WATER, world.player)
                )

            if (world.options.randomize_powers == RandomizePowers.option_off):
                world.get_location(
                    SplasherPowerLocation.STICKINK.fullname()
                ).place_locked_item(
                    SplasherItem(SplasherPowerItem.STICKY, world.player)
                )

                world.get_location(
                    SplasherPowerLocation.BOUNCINK.fullname()
                ).place_locked_item(
                    SplasherItem(SplasherPowerItem.BOUNCY, world.player)
                )

        if not (world.options.randomize_golden_splashers):
            for i in range(22):
                world.get_location(
                    SplashersLocation.fullname(i, None)
                ).place_locked_item(SplasherItem(SplasherUtils.splasher, world.player))

        _Rule.apply(world)

    @staticmethod
    def __add_splashers_rules(world: SplasherWorld):
        rule = Has(SplasherUtils.splasher, world.options.splashers_goal.value)
        for i in range(6):
            _Rule.set(SplashersLocation.fullname(21, i), rule)

        _Rule.set(SplashersLocation.fullname(21, None), rule)
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(21), rule)

    @staticmethod
    def __polluted_water() -> Rule:
        return Has(SplasherPowerItem.WATER) | Has(SplasherPowerItem.PROGRESSIVE_WATER)

    @staticmethod
    def __clean_water() -> Rule:
        return \
            Has(SplasherPowerItem.WATER) | \
            Has(SplasherPowerItem.PROGRESSIVE_WATER, 2) | \
            (Has(SplasherPowerItem.PROGRESSIVE_WATER, 1) & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))

    @staticmethod
    def __speed_water() -> Rule:
        return Has(SplasherPowerItem.WATER) | Has(SplasherPowerItem.PROGRESSIVE_WATER, 3)
    
    @staticmethod
    def __add_power_rules():
        _Rule.set(SplashersLocation.fullname(0, 5), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(0, None), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(0), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(0), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(0), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(0), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(0), SplasherRules.__clean_water())

        _Rule.set(SplashersLocation.fullname(1, 0), SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(1, 1), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(1, 2), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(1, 3), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(1, 4), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(1, 5), SplasherRules.__clean_water())
        _Rule.set(SplashersLocation.fullname(1, None), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(1), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(1), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(1), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(1), SplasherRules.__clean_water())
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(1), SplasherRules.__clean_water())
        
        _Rule.set(SplashersLocation.fullname(2, 0), SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)) # hard with Bouncink
        _Rule.set(SplashersLocation.fullname(2, 1), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(2, 2), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(2, 3), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(2, 4), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(2, 5), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(2, None), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(2), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(2), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(2), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(2), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(2), SplasherRules.__polluted_water())

        _Rule.set(SplashersLocation.fullname(3, 0), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, 1), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, 2), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, 3), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, 4), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, 5), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(3, None), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(3), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(3), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(3), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(3), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(3), SplasherRules.__polluted_water())

        _Rule.set(SplashersLocation.fullname(4, 0), SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(4, 1), SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(4, 2), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(4, 3), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(4, 4), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(4, 5), SplasherRules.__polluted_water())
        _Rule.set(SplashersLocation.fullname(4, None), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(4), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(4), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(4), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(4), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(4), SplasherRules.__polluted_water())

        _Rule.set(SplashersLocation.fullname(5, 0), SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(5, 1), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(5, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(5, 3), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(5, 4), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(5, 5), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(5, None), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplasherPowerLocation.STICKINK.fullname(), SplasherRules.__polluted_water())
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(6, 0), Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(6, 1), Has(SplasherPowerItem.BOUNCY) | (SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(6, 2), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(6, 3), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(6, 4), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(6, 5), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(6, None), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(6), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(6), HasAll(SplasherPowerItem.WATER, SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(6), HasAll(SplasherPowerItem.WATER, SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(6), HasAll(SplasherPowerItem.WATER, SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(6), HasAll(SplasherPowerItem.WATER, SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(7, 0), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(7, 1), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(7, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(7, 3), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(7, 4), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(7, 5), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(7, None), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(7), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(7), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(7), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(7), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(7), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(8, 0), Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(8, 1), Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(8, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(8, 3), Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(8, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(8, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(8, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(8), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(8), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(8), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(8), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(8), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(9, 0), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, 1), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, 3), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, 4), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, 5), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplashersLocation.fullname(9, None), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(9), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.BOUNCY) | Has(SplasherPowerItem.STICKY)))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(9), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(9), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(9), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(9), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(10, 0), Has(SplasherPowerItem.STICKY) & (SplasherRules.__polluted_water() | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(10, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(10, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(10, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(10, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(10, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(10, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(10), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(10), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(10), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(10), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(10), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(11, 0), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, 1), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, 3), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, 4), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, 5), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(11, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(11), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(11), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(11), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(11), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(11), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(12, 0), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(12, 1), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(12, 2), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(12, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(12, 4), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(12, 5), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplashersLocation.fullname(12, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(12), SplasherRules.__polluted_water() & (Has(SplasherPowerItem.STICKY) | Has(SplasherPowerItem.BOUNCY)))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(12), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(12), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(12), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(12), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))

        _Rule.set(SplashersLocation.fullname(13, 0), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(13, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(13, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(13, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(13, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(13, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(13, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(13), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherPowerLocation.BOUNCINK.fullname(), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(13), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(13), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(13), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(13), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(14, 0), Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, 1), Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, 2), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, 3), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, 4), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, 5), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(14, None), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(14), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(14), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(14), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(14), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(14), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(15, 0), Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(15, 1), Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(15, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(15, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(15, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(15, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(15, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(15), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(15), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(15), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(15), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(15), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(16, 0), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(16, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(16), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(16), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(16), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(16), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(16), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(17, 0), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(17, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(17), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(17), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(17), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(17), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(17), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(18, 0), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(18, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(18), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(18), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(18), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(18), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(18), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(19, 0), Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(19, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(19, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(19, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(19, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(19, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(19, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(19), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(19), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(19), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(19), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(19), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(20, 0), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(20, 1), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(20, 2), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(20, 3), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(20, 4), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplashersLocation.fullname(20, 5), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(20, None), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(20), SplasherRules.__polluted_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(20), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(20), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(20), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(20), SplasherRules.__polluted_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

        _Rule.set(SplashersLocation.fullname(21, 0), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, 1), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, 2), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, 3), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, 4), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, 5), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplashersLocation.fullname(21, None), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(21), SplasherRules.__speed_water() & Has(SplasherPowerItem.BOUNCY) & Has(SplasherPowerItem.STICKY))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(21), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(21), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(21), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(21), SplasherRules.__speed_water() & Has(SplasherPowerItem.STICKY) & Has(SplasherPowerItem.BOUNCY))

    @staticmethod
    def __add_progressive_power_rules():
        _Rule.set(SplashersLocation.fullname(0, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(0, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(0), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(1, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(1), Has(SplasherItem.progressive_power, 1))
        
        _Rule.set(SplashersLocation.fullname(2, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(2), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(3, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(3), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(4, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(4), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(5, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(5, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(5, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(5, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(5, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(5, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(5, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherPowerLocation.STICKINK.fullname(), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(5), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(6, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(6, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(6), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(6), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(6), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(6), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(6), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(7, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(7, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(7), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(7), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(7), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(7), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(7), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(8, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(8, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(8), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(8), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(8), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(8), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(8), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(9, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(9, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(9), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(9), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(9), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(9), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(9), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(10, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(10, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(10), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(10), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(10), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(10), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(10), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(11, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(11, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(11), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(11), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(11), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(11), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(11), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(12, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(12, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(12), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(12), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(12), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(12), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(12), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(13, 0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(13, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(13, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(13, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(13, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(13, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(13, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(13), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherPowerLocation.BOUNCINK.fullname(), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(13), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(13), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(13), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(13), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(14, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(14, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(14), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(14), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(14), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(14), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(14), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(15, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(15, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(15), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(15), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(15), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(15), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(15), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(16, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(16, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(16), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(16), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(16), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(16), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(16), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(17, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(17, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(17), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(17), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(17), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(17), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(17), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(18, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(18, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(18), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(18), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(18), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(18), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(18), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(19, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(19, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(19), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(19), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(19), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(19), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(19), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(20, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(20, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(20), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(20), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(20), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(20), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(20), Has(SplasherItem.progressive_power, 3))

        _Rule.set(SplashersLocation.fullname(21, 0), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, 1), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, 2), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, 3), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, 4), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, 5), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplashersLocation.fullname(21, None), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(21), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(21), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(21), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(21), Has(SplasherItem.progressive_power, 3))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(21), Has(SplasherItem.progressive_power, 3))

    @staticmethod
    def __add_progressive_power_rules_with_progressive_water():
        _Rule.set(SplashersLocation.fullname(0, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(0, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(0), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(0), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(1, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(1, 1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(1, 2), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(1, 3), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(1, 4), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(1, 5), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplashersLocation.fullname(1, None), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(1), Has(SplasherItem.progressive_power, 2))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(1), Has(SplasherItem.progressive_power, 2))

        _Rule.set(SplashersLocation.fullname(2, 0), Has(SplasherItem.progressive_power, 1)) # hard with Bouncink
        _Rule.set(SplashersLocation.fullname(2, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(2, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(2), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(3, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(3, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(3), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(4, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 1), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 2), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 3), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, 5), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(4, None), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(4), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(4), Has(SplasherItem.progressive_power, 1))

        _Rule.set(SplashersLocation.fullname(5, 0), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplashersLocation.fullname(5, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(5, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(5, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(5, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(5, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(5, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherPowerLocation.STICKINK.fullname(), Has(SplasherItem.progressive_power, 1))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(5), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(6, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(6, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(6), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(6), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(6), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(6), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(6), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(7, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(7, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(7), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(7), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(7), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(7), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(7), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(8, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(8, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(8), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(8), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(8), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(8), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(8), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(9, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(9, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(9), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(9), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(9), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(9), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(9), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(10, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(10, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(10), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(10), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(10), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(10), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(10), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(11, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(11, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(11), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(11), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(11), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(11), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(11), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(12, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, 1), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, 2), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, 3), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, 4), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, 5), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(12, None), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(12), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(12), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(12), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(12), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(12), Has(SplasherItem.progressive_power, 4))

        _Rule.set(SplashersLocation.fullname(13, 0), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplashersLocation.fullname(13, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(13, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(13, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(13, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(13, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(13, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(13), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherPowerLocation.BOUNCINK.fullname(), Has(SplasherItem.progressive_power, 4))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(13), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(13), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(13), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(13), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(14, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(14, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(14), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(14), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(14), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(14), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(14), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(15, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(15, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(15), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(15), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(15), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(15), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(15), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(16, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(16, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(16), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(16), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(16), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(16), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(16), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(17, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(17, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(17), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(17), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(17), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(17), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(17), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(18, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(18, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(18), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(18), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(18), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(18), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(18), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(19, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(19, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(19), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(19), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(19), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(19), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(19), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(20, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(20, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(20), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(20), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(20), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(20), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(20), Has(SplasherItem.progressive_power, 5))

        _Rule.set(SplashersLocation.fullname(21, 0), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, 1), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, 2), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, 3), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, 4), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, 5), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplashersLocation.fullname(21, None), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.CLEAR.fullname(21), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.BRONZE.fullname(21), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.SILVER.fullname(21), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.GOLD.fullname(21), Has(SplasherItem.progressive_power, 5))
        _Rule.set(SplasherLocationOnEachLevel.PLATINUM.fullname(21), Has(SplasherItem.progressive_power, 5))

class _Rule:
    __rules: ClassVar[dict[str, Rule[SplasherWorld]]] = {}

    @classmethod
    def set(cls, name: str, rule: Rule[SplasherWorld]):
        if name in cls.__rules:
            cls.__rules[name] &= rule
        else:
            cls.__rules[name] = rule
            
    @classmethod
    def apply(cls, world: SplasherWorld):
        locations = frozenset([l.name for l in world.get_locations()])
        
        for name,rule in cls.__rules.items():
            if not name in locations:
                continue # if location not included by options

            world.set_rule(world.get_location(name), rule)

    

        
